### ISSUE TITLE
Is this project still active? Has this been updated for 1.6 - 1.7?

### ISSUE THREAD

**Issue by spindizzyio** [FriendsOfFlarum/github-sponsors#17]
I see there hasnt been an update since 1.0 - is this project still active and does this extension work on the latest version of Flarum? Thanks.

**Comment by imorland** [comment]
Hello @spindizzyio I'm so sorry that noone has responded to you until now.

Yes, this project is still active, it just has not required any updates to maintain support for the current Flarum versions :)
